### PR TITLE
Allow to specify a timeout

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Allow to specify a request timeout

https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback
https://nodejs.org/api/http.html#http_request_abort

### CODE REVIEW

**Comment by ehd** [comment]
Thank you for the contribution! It seems like `request.setTimeout` is not supported yet in browserify, but there's an [open pull request](https://github.com/substack/http-browserify/pull/80). Do you only need this functionality in a node context?

**Comment by johanneswuerbach** [comment]
Yes, I only need it in a node context.

**Comment by johanneswuerbach** [comment]
@ehd anything I could help to push this forward? :-)

**Comment by ehd** [comment]
@johanneswuerbach Sorry for not getting back before. This looks fine to me, and it should work in browsers once http-browserify supports that method.

**Pull request merged**
